name: Running CI Code Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        java-version: [8, 11, 16, 17, 21]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java-varsion }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-varsion }}
        distribution: 'microsoft'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Java Tests
      run: mvn -Dtest=testTesting -DfailIfNoTests=true test
